name: Deploy to Netlify

on:
  push:
    branches: [ main ]
    # Prevent running the entire workflow when changes are made to the README.md
    paths-ignore:
        - 'README.md'


jobs:
  build:
    # This job focuses on building the production-ready version of the application.
    name: Build
    runs-on: ubuntu-latest

    steps:
        # Download the code from the GitHub repository
        - name: Checkout repo
          uses: actions/checkout@v4
  
       # Set up a Node.js environment (version 18) and caches dependencies for efficiency.
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'
  
        - name: Install dependencies
          run: npm install
  
        - name: Build project
          run: npm run build
        #   Upload production-ready built files as an artifac
        - name: Upload production-ready built files
          uses: actions/upload-artifact@v4
          with:
            # Upload dist directory
            name: production-files
            path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # Only run if the triggering branch is refs/heads/main, ensuring deployments only happen from the main branch.
    if: github.ref == 'refs/heads/main'

    steps:
        # Download the production-ready files (named production-files) generated by the build job and stores them in the ./dist directory.
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: production-files
            path: ./dist
        # Utilise the below action to deploy the downloaded files to your Netlify.
        - name: Deploy to Netlify Account
          uses: jsmrcaga/action-netlify-deploy@v2.0.0
          with:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN_SECRET }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_MESSAGE: 'Deployed to dev'
            publish_dir: ./dist
    