name: CI & CD to Netlify

on:
  push:
    branches: [ main ]
    # Prevent running the entire workflow when changes are made to the README.md
    paths-ignore:
        - 'README.md'


jobs:
  build_deploy:
    # This job focuses on building the production-ready version of the application.
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
        # Download the code from the GitHub repository
        - name: Checkout repo
          uses: actions/checkout@v4
  
       # Set up a Node.js environment (version 20) and caches dependencies for efficiency.
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
  
        - name: Install dependencies
          run: npm install
  
        - name: Build project
          run: npm run build

        - name: Deploy to Netlify
          uses: jsmrcaga/action-netlify-deploy@master
          with:
            build_directory: './dist'
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN_SECRET }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub Actions as version: ${{ github.event.head_commit.id}}"
            NETLIFY_DEPLOY_TO_PROD: true
