name: 'PR Preview'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']
    # Prevent running the entire workflow when changes are made to the README.md
    paths-ignore:
      - 'README.md'

jobs:
  build-and-deploy-preview:
    # This job focuses on building the application and deploying a preview to Netlify.
    name: Build & Deploy Preview
    runs-on: ubuntu-latest

    steps:
      # Download the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up a Node.js environment (version 20) and caches dependencies for efficiency.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy Preview to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          build_directory: './dist'
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy preview: Pull Request #${{ github.event.number }}"